name: "Release to Maven Central"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    env:
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: ./res/.java-version
      - name: Check JRelease Configs
        run: ./mvnw -Prelease jreleaser:config
      - name: Publish package
        run: ./mvnw -Prelease deploy jreleaser:deploy